// The contract between the Go server and the Rust storage engine.
//
// The boundary is gRPC over a local socket rather than cgo. cgo would put a
// segfault in the storage engine inside the server's address space, make every
// call cross the Go scheduler's boundary, and complicate the build for both
// languages. A local gRPC hop costs tens of microseconds and buys a hard fault
// boundary, two independently profileable processes, and a seam that already
// works when the engine moves to another host.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: engine.proto

package enginepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Record is a stored value and its absolute expiry.
type Record struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The value bytes.
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Absolute expiry in Unix milliseconds, or zero for never.
	//
	// Absolute rather than relative is a durability requirement, not a style
	// choice: a relative TTL replayed from a log hours after it was written would
	// silently extend every key's life by the length of the outage.
	ExpireAt      int64 `protobuf:"varint,2,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Record) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

// GetRequest asks for one key.
type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Wall time the read is evaluated against, so expiry decisions come from the
	// caller's clock rather than the engine's. With two processes involved, a
	// single authoritative clock is the only way TTLs stay consistent.
	NowMs         int64 `protobuf:"varint,2,opt,name=now_ms,json=nowMs,proto3" json:"now_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetRequest) GetNowMs() int64 {
	if x != nil {
		return x.NowMs
	}
	return 0
}

// GetResponse carries the record, if the key is live.
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Record        *Record                `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

// PutRequest writes one key.
type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Record        *Record                `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{3}
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

// PutResponse acknowledges a write.
type PutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The engine sequence number the write was assigned.
	Sequence      uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{4}
}

func (x *PutResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// DeleteRequest removes one key.
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	NowMs         int64                  `protobuf:"varint,2,opt,name=now_ms,json=nowMs,proto3" json:"now_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DeleteRequest) GetNowMs() int64 {
	if x != nil {
		return x.NowMs
	}
	return 0
}

// DeleteResponse reports whether a live record was present.
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Existed       bool                   `protobuf:"varint,1,opt,name=existed,proto3" json:"existed,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteResponse) GetExisted() bool {
	if x != nil {
		return x.Existed
	}
	return false
}

func (x *DeleteResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// Mutation is one write in a batch.
type Mutation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Absent means delete.
	Record        *Record `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	Delete        bool    `protobuf:"varint,3,opt,name=delete,proto3" json:"delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	mi := &file_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{7}
}

func (x *Mutation) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Mutation) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *Mutation) GetDelete() bool {
	if x != nil {
		return x.Delete
	}
	return false
}

// BatchWriteRequest applies several mutations as one log record.
type BatchWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mutations     []*Mutation            `protobuf:"bytes,1,rep,name=mutations,proto3" json:"mutations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchWriteRequest) Reset() {
	*x = BatchWriteRequest{}
	mi := &file_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchWriteRequest) ProtoMessage() {}

func (x *BatchWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchWriteRequest.ProtoReflect.Descriptor instead.
func (*BatchWriteRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{8}
}

func (x *BatchWriteRequest) GetMutations() []*Mutation {
	if x != nil {
		return x.Mutations
	}
	return nil
}

// BatchWriteResponse acknowledges a batch.
type BatchWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchWriteResponse) Reset() {
	*x = BatchWriteResponse{}
	mi := &file_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchWriteResponse) ProtoMessage() {}

func (x *BatchWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchWriteResponse.ProtoReflect.Descriptor instead.
func (*BatchWriteResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{9}
}

func (x *BatchWriteResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// ScanRequest asks for a page of the keyspace.
type ScanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resume from this key inclusive. Empty starts at the beginning.
	Start []byte `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	// Maximum records to return.
	Limit         uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	NowMs         int64  `protobuf:"varint,3,opt,name=now_ms,json=nowMs,proto3" json:"now_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{10}
}

func (x *ScanRequest) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ScanRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ScanRequest) GetNowMs() int64 {
	if x != nil {
		return x.NowMs
	}
	return 0
}

// KeyValue is one scanned record.
type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Record        *Record                `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{11}
}

func (x *KeyValue) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValue) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

// ScanResponse carries a page and where to resume.
type ScanResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Entries []*KeyValue            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// Where the next page starts. Absent means the walk is finished.
	NextStart     []byte `protobuf:"bytes,2,opt,name=next_start,json=nextStart,proto3" json:"next_start,omitempty"`
	HasMore       bool   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{12}
}

func (x *ScanResponse) GetEntries() []*KeyValue {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ScanResponse) GetNextStart() []byte {
	if x != nil {
		return x.NextStart
	}
	return nil
}

func (x *ScanResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// FlushAllRequest removes every key.
type FlushAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushAllRequest) Reset() {
	*x = FlushAllRequest{}
	mi := &file_engine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushAllRequest) ProtoMessage() {}

func (x *FlushAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushAllRequest.ProtoReflect.Descriptor instead.
func (*FlushAllRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{13}
}

// FlushAllResponse acknowledges the wipe.
type FlushAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeysRemoved   uint64                 `protobuf:"varint,1,opt,name=keys_removed,json=keysRemoved,proto3" json:"keys_removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushAllResponse) Reset() {
	*x = FlushAllResponse{}
	mi := &file_engine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushAllResponse) ProtoMessage() {}

func (x *FlushAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushAllResponse.ProtoReflect.Descriptor instead.
func (*FlushAllResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{14}
}

func (x *FlushAllResponse) GetKeysRemoved() uint64 {
	if x != nil {
		return x.KeysRemoved
	}
	return 0
}

// SyncRequest forces acknowledged writes to stable storage.
type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_engine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{15}
}

// SyncResponse acknowledges the fsync.
type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_engine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{16}
}

// FlushRequest writes the memtable out as an SSTable.
type FlushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushRequest) Reset() {
	*x = FlushRequest{}
	mi := &file_engine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushRequest) ProtoMessage() {}

func (x *FlushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushRequest.ProtoReflect.Descriptor instead.
func (*FlushRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{17}
}

// FlushResponse acknowledges the flush.
type FlushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushResponse) Reset() {
	*x = FlushResponse{}
	mi := &file_engine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushResponse) ProtoMessage() {}

func (x *FlushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushResponse.ProtoReflect.Descriptor instead.
func (*FlushResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{18}
}

// CompactRequest runs compaction to completion.
type CompactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactRequest) Reset() {
	*x = CompactRequest{}
	mi := &file_engine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactRequest) ProtoMessage() {}

func (x *CompactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactRequest.ProtoReflect.Descriptor instead.
func (*CompactRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{19}
}

// CompactResponse acknowledges the compaction.
type CompactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactResponse) Reset() {
	*x = CompactResponse{}
	mi := &file_engine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactResponse) ProtoMessage() {}

func (x *CompactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactResponse.ProtoReflect.Descriptor instead.
func (*CompactResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{20}
}

// StatsRequest asks for engine counters.
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NowMs         int64                  `protobuf:"varint,1,opt,name=now_ms,json=nowMs,proto3" json:"now_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_engine_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{21}
}

func (x *StatsRequest) GetNowMs() int64 {
	if x != nil {
		return x.NowMs
	}
	return 0
}

// StatsResponse reports engine counters.
type StatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Live keys, estimated. Over-counts keys present at several levels and
	// tombstones not yet compacted away; an exact count needs a full merge, which
	// is why this is labelled an estimate everywhere it surfaces.
	KeysEstimate           uint64   `protobuf:"varint,1,opt,name=keys_estimate,json=keysEstimate,proto3" json:"keys_estimate,omitempty"`
	DiskBytes              uint64   `protobuf:"varint,2,opt,name=disk_bytes,json=diskBytes,proto3" json:"disk_bytes,omitempty"`
	MemoryBytes            uint64   `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	LevelFiles             []uint64 `protobuf:"varint,4,rep,packed,name=level_files,json=levelFiles,proto3" json:"level_files,omitempty"`
	LevelBytes             []uint64 `protobuf:"varint,5,rep,packed,name=level_bytes,json=levelBytes,proto3" json:"level_bytes,omitempty"`
	Writes                 uint64   `protobuf:"varint,6,opt,name=writes,proto3" json:"writes,omitempty"`
	Reads                  uint64   `protobuf:"varint,7,opt,name=reads,proto3" json:"reads,omitempty"`
	Flushes                uint64   `protobuf:"varint,8,opt,name=flushes,proto3" json:"flushes,omitempty"`
	Compactions            uint64   `protobuf:"varint,9,opt,name=compactions,proto3" json:"compactions,omitempty"`
	CompactionBytesRead    uint64   `protobuf:"varint,10,opt,name=compaction_bytes_read,json=compactionBytesRead,proto3" json:"compaction_bytes_read,omitempty"`
	CompactionBytesWritten uint64   `protobuf:"varint,11,opt,name=compaction_bytes_written,json=compactionBytesWritten,proto3" json:"compaction_bytes_written,omitempty"`
	WriteStalls            uint64   `protobuf:"varint,12,opt,name=write_stalls,json=writeStalls,proto3" json:"write_stalls,omitempty"`
	BloomRejections        uint64   `protobuf:"varint,13,opt,name=bloom_rejections,json=bloomRejections,proto3" json:"bloom_rejections,omitempty"`
	SstableReads           uint64   `protobuf:"varint,14,opt,name=sstable_reads,json=sstableReads,proto3" json:"sstable_reads,omitempty"`
	WalAppends             uint64   `protobuf:"varint,15,opt,name=wal_appends,json=walAppends,proto3" json:"wal_appends,omitempty"`
	WalWrites              uint64   `protobuf:"varint,16,opt,name=wal_writes,json=walWrites,proto3" json:"wal_writes,omitempty"`
	WalFsyncs              uint64   `protobuf:"varint,17,opt,name=wal_fsyncs,json=walFsyncs,proto3" json:"wal_fsyncs,omitempty"`
	WalBytes               uint64   `protobuf:"varint,18,opt,name=wal_bytes,json=walBytes,proto3" json:"wal_bytes,omitempty"`
	// Acknowledged records not yet on stable storage. This is the exact size of
	// the window a power cut would lose.
	WalUnsynced uint64 `protobuf:"varint,19,opt,name=wal_unsynced,json=walUnsynced,proto3" json:"wal_unsynced,omitempty"`
	WalPolicy   string `protobuf:"bytes,20,opt,name=wal_policy,json=walPolicy,proto3" json:"wal_policy,omitempty"`
	Version     string `protobuf:"bytes,21,opt,name=version,proto3" json:"version,omitempty"`
	// Set when the last recovery discarded an incomplete record from the end of
	// the log. An operator must never have to infer that.
	RecoveryTruncated  bool   `protobuf:"varint,22,opt,name=recovery_truncated,json=recoveryTruncated,proto3" json:"recovery_truncated,omitempty"`
	RecoveryLogBatches uint64 `protobuf:"varint,23,opt,name=recovery_log_batches,json=recoveryLogBatches,proto3" json:"recovery_log_batches,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_engine_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{22}
}

func (x *StatsResponse) GetKeysEstimate() uint64 {
	if x != nil {
		return x.KeysEstimate
	}
	return 0
}

func (x *StatsResponse) GetDiskBytes() uint64 {
	if x != nil {
		return x.DiskBytes
	}
	return 0
}

func (x *StatsResponse) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *StatsResponse) GetLevelFiles() []uint64 {
	if x != nil {
		return x.LevelFiles
	}
	return nil
}

func (x *StatsResponse) GetLevelBytes() []uint64 {
	if x != nil {
		return x.LevelBytes
	}
	return nil
}

func (x *StatsResponse) GetWrites() uint64 {
	if x != nil {
		return x.Writes
	}
	return 0
}

func (x *StatsResponse) GetReads() uint64 {
	if x != nil {
		return x.Reads
	}
	return 0
}

func (x *StatsResponse) GetFlushes() uint64 {
	if x != nil {
		return x.Flushes
	}
	return 0
}

func (x *StatsResponse) GetCompactions() uint64 {
	if x != nil {
		return x.Compactions
	}
	return 0
}

func (x *StatsResponse) GetCompactionBytesRead() uint64 {
	if x != nil {
		return x.CompactionBytesRead
	}
	return 0
}

func (x *StatsResponse) GetCompactionBytesWritten() uint64 {
	if x != nil {
		return x.CompactionBytesWritten
	}
	return 0
}

func (x *StatsResponse) GetWriteStalls() uint64 {
	if x != nil {
		return x.WriteStalls
	}
	return 0
}

func (x *StatsResponse) GetBloomRejections() uint64 {
	if x != nil {
		return x.BloomRejections
	}
	return 0
}

func (x *StatsResponse) GetSstableReads() uint64 {
	if x != nil {
		return x.SstableReads
	}
	return 0
}

func (x *StatsResponse) GetWalAppends() uint64 {
	if x != nil {
		return x.WalAppends
	}
	return 0
}

func (x *StatsResponse) GetWalWrites() uint64 {
	if x != nil {
		return x.WalWrites
	}
	return 0
}

func (x *StatsResponse) GetWalFsyncs() uint64 {
	if x != nil {
		return x.WalFsyncs
	}
	return 0
}

func (x *StatsResponse) GetWalBytes() uint64 {
	if x != nil {
		return x.WalBytes
	}
	return 0
}

func (x *StatsResponse) GetWalUnsynced() uint64 {
	if x != nil {
		return x.WalUnsynced
	}
	return 0
}

func (x *StatsResponse) GetWalPolicy() string {
	if x != nil {
		return x.WalPolicy
	}
	return ""
}

func (x *StatsResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatsResponse) GetRecoveryTruncated() bool {
	if x != nil {
		return x.RecoveryTruncated
	}
	return false
}

func (x *StatsResponse) GetRecoveryLogBatches() uint64 {
	if x != nil {
		return x.RecoveryLogBatches
	}
	return 0
}

var File_engine_proto protoreflect.FileDescriptor

const file_engine_proto_rawDesc = "" +
	"\n" +
	"\fengine.proto\x12\rrfs.engine.v1\";\n" +
	"\x06Record\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x1b\n" +
	"\texpire_at\x18\x02 \x01(\x03R\bexpireAt\"5\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x15\n" +
	"\x06now_ms\x18\x02 \x01(\x03R\x05nowMs\"R\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12-\n" +
	"\x06record\x18\x02 \x01(\v2\x15.rfs.engine.v1.RecordR\x06record\"M\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12-\n" +
	"\x06record\x18\x02 \x01(\v2\x15.rfs.engine.v1.RecordR\x06record\")\n" +
	"\vPutResponse\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\"8\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x15\n" +
	"\x06now_ms\x18\x02 \x01(\x03R\x05nowMs\"F\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\aexisted\x18\x01 \x01(\bR\aexisted\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\"c\n" +
	"\bMutation\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12-\n" +
	"\x06record\x18\x02 \x01(\v2\x15.rfs.engine.v1.RecordR\x06record\x12\x16\n" +
	"\x06delete\x18\x03 \x01(\bR\x06delete\"J\n" +
	"\x11BatchWriteRequest\x125\n" +
	"\tmutations\x18\x01 \x03(\v2\x17.rfs.engine.v1.MutationR\tmutations\"0\n" +
	"\x12BatchWriteResponse\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\"P\n" +
	"\vScanRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\fR\x05start\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x15\n" +
	"\x06now_ms\x18\x03 \x01(\x03R\x05nowMs\"K\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12-\n" +
	"\x06record\x18\x02 \x01(\v2\x15.rfs.engine.v1.RecordR\x06record\"{\n" +
	"\fScanResponse\x121\n" +
	"\aentries\x18\x01 \x03(\v2\x17.rfs.engine.v1.KeyValueR\aentries\x12\x1d\n" +
	"\n" +
	"next_start\x18\x02 \x01(\fR\tnextStart\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\x11\n" +
	"\x0fFlushAllRequest\"5\n" +
	"\x10FlushAllResponse\x12!\n" +
	"\fkeys_removed\x18\x01 \x01(\x04R\vkeysRemoved\"\r\n" +
	"\vSyncRequest\"\x0e\n" +
	"\fSyncResponse\"\x0e\n" +
	"\fFlushRequest\"\x0f\n" +
	"\rFlushResponse\"\x10\n" +
	"\x0eCompactRequest\"\x11\n" +
	"\x0fCompactResponse\"%\n" +
	"\fStatsRequest\x12\x15\n" +
	"\x06now_ms\x18\x01 \x01(\x03R\x05nowMs\"\xbc\x06\n" +
	"\rStatsResponse\x12#\n" +
	"\rkeys_estimate\x18\x01 \x01(\x04R\fkeysEstimate\x12\x1d\n" +
	"\n" +
	"disk_bytes\x18\x02 \x01(\x04R\tdiskBytes\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x04R\vmemoryBytes\x12\x1f\n" +
	"\vlevel_files\x18\x04 \x03(\x04R\n" +
	"levelFiles\x12\x1f\n" +
	"\vlevel_bytes\x18\x05 \x03(\x04R\n" +
	"levelBytes\x12\x16\n" +
	"\x06writes\x18\x06 \x01(\x04R\x06writes\x12\x14\n" +
	"\x05reads\x18\a \x01(\x04R\x05reads\x12\x18\n" +
	"\aflushes\x18\b \x01(\x04R\aflushes\x12 \n" +
	"\vcompactions\x18\t \x01(\x04R\vcompactions\x122\n" +
	"\x15compaction_bytes_read\x18\n" +
	" \x01(\x04R\x13compactionBytesRead\x128\n" +
	"\x18compaction_bytes_written\x18\v \x01(\x04R\x16compactionBytesWritten\x12!\n" +
	"\fwrite_stalls\x18\f \x01(\x04R\vwriteStalls\x12)\n" +
	"\x10bloom_rejections\x18\r \x01(\x04R\x0fbloomRejections\x12#\n" +
	"\rsstable_reads\x18\x0e \x01(\x04R\fsstableReads\x12\x1f\n" +
	"\vwal_appends\x18\x0f \x01(\x04R\n" +
	"walAppends\x12\x1d\n" +
	"\n" +
	"wal_writes\x18\x10 \x01(\x04R\twalWrites\x12\x1d\n" +
	"\n" +
	"wal_fsyncs\x18\x11 \x01(\x04R\twalFsyncs\x12\x1b\n" +
	"\twal_bytes\x18\x12 \x01(\x04R\bwalBytes\x12!\n" +
	"\fwal_unsynced\x18\x13 \x01(\x04R\vwalUnsynced\x12\x1d\n" +
	"\n" +
	"wal_policy\x18\x14 \x01(\tR\twalPolicy\x12\x18\n" +
	"\aversion\x18\x15 \x01(\tR\aversion\x12-\n" +
	"\x12recovery_truncated\x18\x16 \x01(\bR\x11recoveryTruncated\x120\n" +
	"\x14recovery_log_batches\x18\x17 \x01(\x04R\x12recoveryLogBatches2\xc6\x05\n" +
	"\rStorageEngine\x12<\n" +
	"\x03Get\x12\x19.rfs.engine.v1.GetRequest\x1a\x1a.rfs.engine.v1.GetResponse\x12<\n" +
	"\x03Put\x12\x19.rfs.engine.v1.PutRequest\x1a\x1a.rfs.engine.v1.PutResponse\x12E\n" +
	"\x06Delete\x12\x1c.rfs.engine.v1.DeleteRequest\x1a\x1d.rfs.engine.v1.DeleteResponse\x12Q\n" +
	"\n" +
	"BatchWrite\x12 .rfs.engine.v1.BatchWriteRequest\x1a!.rfs.engine.v1.BatchWriteResponse\x12?\n" +
	"\x04Scan\x12\x1a.rfs.engine.v1.ScanRequest\x1a\x1b.rfs.engine.v1.ScanResponse\x12K\n" +
	"\bFlushAll\x12\x1e.rfs.engine.v1.FlushAllRequest\x1a\x1f.rfs.engine.v1.FlushAllResponse\x12?\n" +
	"\x04Sync\x12\x1a.rfs.engine.v1.SyncRequest\x1a\x1b.rfs.engine.v1.SyncResponse\x12B\n" +
	"\x05Flush\x12\x1b.rfs.engine.v1.FlushRequest\x1a\x1c.rfs.engine.v1.FlushResponse\x12H\n" +
	"\aCompact\x12\x1d.rfs.engine.v1.CompactRequest\x1a\x1e.rfs.engine.v1.CompactResponse\x12B\n" +
	"\x05Stats\x12\x1b.rfs.engine.v1.StatsRequest\x1a\x1c.rfs.engine.v1.StatsResponseBIZGgithub.com/CosmicSaaurabh/redis-from-scratch/internal/enginepb;enginepbb\x06proto3"

var (
	file_engine_proto_rawDescOnce sync.Once
	file_engine_proto_rawDescData []byte
)

func file_engine_proto_rawDescGZIP() []byte {
	file_engine_proto_rawDescOnce.Do(func() {
		file_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)))
	})
	return file_engine_proto_rawDescData
}

var file_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_engine_proto_goTypes = []any{
	(*Record)(nil),             // 0: rfs.engine.v1.Record
	(*GetRequest)(nil),         // 1: rfs.engine.v1.GetRequest
	(*GetResponse)(nil),        // 2: rfs.engine.v1.GetResponse
	(*PutRequest)(nil),         // 3: rfs.engine.v1.PutRequest
	(*PutResponse)(nil),        // 4: rfs.engine.v1.PutResponse
	(*DeleteRequest)(nil),      // 5: rfs.engine.v1.DeleteRequest
	(*DeleteResponse)(nil),     // 6: rfs.engine.v1.DeleteResponse
	(*Mutation)(nil),           // 7: rfs.engine.v1.Mutation
	(*BatchWriteRequest)(nil),  // 8: rfs.engine.v1.BatchWriteRequest
	(*BatchWriteResponse)(nil), // 9: rfs.engine.v1.BatchWriteResponse
	(*ScanRequest)(nil),        // 10: rfs.engine.v1.ScanRequest
	(*KeyValue)(nil),           // 11: rfs.engine.v1.KeyValue
	(*ScanResponse)(nil),       // 12: rfs.engine.v1.ScanResponse
	(*FlushAllRequest)(nil),    // 13: rfs.engine.v1.FlushAllRequest
	(*FlushAllResponse)(nil),   // 14: rfs.engine.v1.FlushAllResponse
	(*SyncRequest)(nil),        // 15: rfs.engine.v1.SyncRequest
	(*SyncResponse)(nil),       // 16: rfs.engine.v1.SyncResponse
	(*FlushRequest)(nil),       // 17: rfs.engine.v1.FlushRequest
	(*FlushResponse)(nil),      // 18: rfs.engine.v1.FlushResponse
	(*CompactRequest)(nil),     // 19: rfs.engine.v1.CompactRequest
	(*CompactResponse)(nil),    // 20: rfs.engine.v1.CompactResponse
	(*StatsRequest)(nil),       // 21: rfs.engine.v1.StatsRequest
	(*StatsResponse)(nil),      // 22: rfs.engine.v1.StatsResponse
}
var file_engine_proto_depIdxs = []int32{
	0,  // 0: rfs.engine.v1.GetResponse.record:type_name -> rfs.engine.v1.Record
	0,  // 1: rfs.engine.v1.PutRequest.record:type_name -> rfs.engine.v1.Record
	0,  // 2: rfs.engine.v1.Mutation.record:type_name -> rfs.engine.v1.Record
	7,  // 3: rfs.engine.v1.BatchWriteRequest.mutations:type_name -> rfs.engine.v1.Mutation
	0,  // 4: rfs.engine.v1.KeyValue.record:type_name -> rfs.engine.v1.Record
	11, // 5: rfs.engine.v1.ScanResponse.entries:type_name -> rfs.engine.v1.KeyValue
	1,  // 6: rfs.engine.v1.StorageEngine.Get:input_type -> rfs.engine.v1.GetRequest
	3,  // 7: rfs.engine.v1.StorageEngine.Put:input_type -> rfs.engine.v1.PutRequest
	5,  // 8: rfs.engine.v1.StorageEngine.Delete:input_type -> rfs.engine.v1.DeleteRequest
	8,  // 9: rfs.engine.v1.StorageEngine.BatchWrite:input_type -> rfs.engine.v1.BatchWriteRequest
	10, // 10: rfs.engine.v1.StorageEngine.Scan:input_type -> rfs.engine.v1.ScanRequest
	13, // 11: rfs.engine.v1.StorageEngine.FlushAll:input_type -> rfs.engine.v1.FlushAllRequest
	15, // 12: rfs.engine.v1.StorageEngine.Sync:input_type -> rfs.engine.v1.SyncRequest
	17, // 13: rfs.engine.v1.StorageEngine.Flush:input_type -> rfs.engine.v1.FlushRequest
	19, // 14: rfs.engine.v1.StorageEngine.Compact:input_type -> rfs.engine.v1.CompactRequest
	21, // 15: rfs.engine.v1.StorageEngine.Stats:input_type -> rfs.engine.v1.StatsRequest
	2,  // 16: rfs.engine.v1.StorageEngine.Get:output_type -> rfs.engine.v1.GetResponse
	4,  // 17: rfs.engine.v1.StorageEngine.Put:output_type -> rfs.engine.v1.PutResponse
	6,  // 18: rfs.engine.v1.StorageEngine.Delete:output_type -> rfs.engine.v1.DeleteResponse
	9,  // 19: rfs.engine.v1.StorageEngine.BatchWrite:output_type -> rfs.engine.v1.BatchWriteResponse
	12, // 20: rfs.engine.v1.StorageEngine.Scan:output_type -> rfs.engine.v1.ScanResponse
	14, // 21: rfs.engine.v1.StorageEngine.FlushAll:output_type -> rfs.engine.v1.FlushAllResponse
	16, // 22: rfs.engine.v1.StorageEngine.Sync:output_type -> rfs.engine.v1.SyncResponse
	18, // 23: rfs.engine.v1.StorageEngine.Flush:output_type -> rfs.engine.v1.FlushResponse
	20, // 24: rfs.engine.v1.StorageEngine.Compact:output_type -> rfs.engine.v1.CompactResponse
	22, // 25: rfs.engine.v1.StorageEngine.Stats:output_type -> rfs.engine.v1.StatsResponse
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_engine_proto_init() }
func file_engine_proto_init() {
	if File_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engine_proto_goTypes,
		DependencyIndexes: file_engine_proto_depIdxs,
		MessageInfos:      file_engine_proto_msgTypes,
	}.Build()
	File_engine_proto = out.File
	file_engine_proto_goTypes = nil
	file_engine_proto_depIdxs = nil
}
