// The contract between the Go server and the Rust storage engine.
//
// The boundary is gRPC over a local socket rather than cgo. cgo would put a
// segfault in the storage engine inside the server's address space, make every
// call cross the Go scheduler's boundary, and complicate the build for both
// languages. A local gRPC hop costs tens of microseconds and buys a hard fault
// boundary, two independently profileable processes, and a seam that already
// works when the engine moves to another host.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.1
// source: engine.proto

package enginepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageEngine_Get_FullMethodName        = "/rfs.engine.v1.StorageEngine/Get"
	StorageEngine_Put_FullMethodName        = "/rfs.engine.v1.StorageEngine/Put"
	StorageEngine_Delete_FullMethodName     = "/rfs.engine.v1.StorageEngine/Delete"
	StorageEngine_BatchWrite_FullMethodName = "/rfs.engine.v1.StorageEngine/BatchWrite"
	StorageEngine_Scan_FullMethodName       = "/rfs.engine.v1.StorageEngine/Scan"
	StorageEngine_FlushAll_FullMethodName   = "/rfs.engine.v1.StorageEngine/FlushAll"
	StorageEngine_Sync_FullMethodName       = "/rfs.engine.v1.StorageEngine/Sync"
	StorageEngine_Flush_FullMethodName      = "/rfs.engine.v1.StorageEngine/Flush"
	StorageEngine_Compact_FullMethodName    = "/rfs.engine.v1.StorageEngine/Compact"
	StorageEngine_Stats_FullMethodName      = "/rfs.engine.v1.StorageEngine/Stats"
)

// StorageEngineClient is the client API for StorageEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StorageEngine is the pluggable storage boundary as seen over the wire.
//
// It carries no Redis semantics. There is no INCR and no SET NX here, because
// those are command-layer concerns; the engine offers reads, writes and an
// ordered scan, and the server composes the rest. Keeping Redis out of this
// interface is what lets the same engine sit behind something that is not
// Redis later.
type StorageEngineClient interface {
	// Get reads one key.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// Put writes one key.
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	// Delete removes one key.
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// BatchWrite applies several mutations atomically with respect to recovery.
	BatchWrite(ctx context.Context, in *BatchWriteRequest, opts ...grpc.CallOption) (*BatchWriteResponse, error)
	// Scan walks the keyspace in key order.
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
	// FlushAll removes every key.
	FlushAll(ctx context.Context, in *FlushAllRequest, opts ...grpc.CallOption) (*FlushAllResponse, error)
	// Sync forces acknowledged writes to stable storage.
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	// Flush freezes the memtable and writes it out as an SSTable.
	Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error)
	// Compact runs compaction until every level is inside its budget.
	Compact(ctx context.Context, in *CompactRequest, opts ...grpc.CallOption) (*CompactResponse, error)
	// Stats reports engine counters.
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type storageEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageEngineClient(cc grpc.ClientConnInterface) StorageEngineClient {
	return &storageEngineClient{cc}
}

func (c *storageEngineClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, StorageEngine_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageEngineClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, StorageEngine_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageEngineClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, StorageEngine_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageEngineClient) BatchWrite(ctx context.Context, in *BatchWriteRequest, opts ...grpc.CallOption) (*BatchWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchWriteResponse)
	err := c.cc.Invoke(ctx, StorageEngine_BatchWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageEngineClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, StorageEngine_Scan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageEngineClient) FlushAll(ctx context.Context, in *FlushAllRequest, opts ...grpc.CallOption) (*FlushAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushAllResponse)
	err := c.cc.Invoke(ctx, StorageEngine_FlushAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageEngineClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, StorageEngine_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageEngineClient) Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushResponse)
	err := c.cc.Invoke(ctx, StorageEngine_Flush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageEngineClient) Compact(ctx context.Context, in *CompactRequest, opts ...grpc.CallOption) (*CompactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompactResponse)
	err := c.cc.Invoke(ctx, StorageEngine_Compact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageEngineClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, StorageEngine_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageEngineServer is the server API for StorageEngine service.
// All implementations must embed UnimplementedStorageEngineServer
// for forward compatibility.
//
// StorageEngine is the pluggable storage boundary as seen over the wire.
//
// It carries no Redis semantics. There is no INCR and no SET NX here, because
// those are command-layer concerns; the engine offers reads, writes and an
// ordered scan, and the server composes the rest. Keeping Redis out of this
// interface is what lets the same engine sit behind something that is not
// Redis later.
type StorageEngineServer interface {
	// Get reads one key.
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// Put writes one key.
	Put(context.Context, *PutRequest) (*PutResponse, error)
	// Delete removes one key.
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// BatchWrite applies several mutations atomically with respect to recovery.
	BatchWrite(context.Context, *BatchWriteRequest) (*BatchWriteResponse, error)
	// Scan walks the keyspace in key order.
	Scan(context.Context, *ScanRequest) (*ScanResponse, error)
	// FlushAll removes every key.
	FlushAll(context.Context, *FlushAllRequest) (*FlushAllResponse, error)
	// Sync forces acknowledged writes to stable storage.
	Sync(context.Context, *SyncRequest) (*SyncResponse, error)
	// Flush freezes the memtable and writes it out as an SSTable.
	Flush(context.Context, *FlushRequest) (*FlushResponse, error)
	// Compact runs compaction until every level is inside its budget.
	Compact(context.Context, *CompactRequest) (*CompactResponse, error)
	// Stats reports engine counters.
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	mustEmbedUnimplementedStorageEngineServer()
}

// UnimplementedStorageEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageEngineServer struct{}

func (UnimplementedStorageEngineServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedStorageEngineServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedStorageEngineServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedStorageEngineServer) BatchWrite(context.Context, *BatchWriteRequest) (*BatchWriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchWrite not implemented")
}
func (UnimplementedStorageEngineServer) Scan(context.Context, *ScanRequest) (*ScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedStorageEngineServer) FlushAll(context.Context, *FlushAllRequest) (*FlushAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FlushAll not implemented")
}
func (UnimplementedStorageEngineServer) Sync(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedStorageEngineServer) Flush(context.Context, *FlushRequest) (*FlushResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Flush not implemented")
}
func (UnimplementedStorageEngineServer) Compact(context.Context, *CompactRequest) (*CompactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Compact not implemented")
}
func (UnimplementedStorageEngineServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedStorageEngineServer) mustEmbedUnimplementedStorageEngineServer() {}
func (UnimplementedStorageEngineServer) testEmbeddedByValue()                       {}

// UnsafeStorageEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageEngineServer will
// result in compilation errors.
type UnsafeStorageEngineServer interface {
	mustEmbedUnimplementedStorageEngineServer()
}

func RegisterStorageEngineServer(s grpc.ServiceRegistrar, srv StorageEngineServer) {
	// If the following call panics, it indicates UnimplementedStorageEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageEngine_ServiceDesc, srv)
}

func _StorageEngine_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageEngineServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageEngine_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageEngineServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageEngine_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageEngineServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageEngine_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageEngineServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageEngine_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageEngineServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageEngine_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageEngineServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageEngine_BatchWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageEngineServer).BatchWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageEngine_BatchWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageEngineServer).BatchWrite(ctx, req.(*BatchWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageEngine_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageEngineServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageEngine_Scan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageEngineServer).Scan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageEngine_FlushAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageEngineServer).FlushAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageEngine_FlushAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageEngineServer).FlushAll(ctx, req.(*FlushAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageEngine_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageEngineServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageEngine_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageEngineServer).Sync(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageEngine_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageEngineServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageEngine_Flush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageEngineServer).Flush(ctx, req.(*FlushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageEngine_Compact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageEngineServer).Compact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageEngine_Compact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageEngineServer).Compact(ctx, req.(*CompactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageEngine_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageEngineServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageEngine_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageEngineServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageEngine_ServiceDesc is the grpc.ServiceDesc for StorageEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rfs.engine.v1.StorageEngine",
	HandlerType: (*StorageEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _StorageEngine_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _StorageEngine_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _StorageEngine_Delete_Handler,
		},
		{
			MethodName: "BatchWrite",
			Handler:    _StorageEngine_BatchWrite_Handler,
		},
		{
			MethodName: "Scan",
			Handler:    _StorageEngine_Scan_Handler,
		},
		{
			MethodName: "FlushAll",
			Handler:    _StorageEngine_FlushAll_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _StorageEngine_Sync_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _StorageEngine_Flush_Handler,
		},
		{
			MethodName: "Compact",
			Handler:    _StorageEngine_Compact_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _StorageEngine_Stats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "engine.proto",
}
